-- MySQL Script generated by MySQL Workbench
-- Mon Aug 22 13:02:04 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Question Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Question Type` (
  `idQuestion Type` INT NOT NULL,
  `QuestionTypeName` VARCHAR(45) NOT NULL,
  `isMultipleChoice` TINYINT NULL DEFAULT 1,
  `isFreeFormNumeric` TINYINT NULL DEFAULT 1,
  `isFreeFormNonNumeric` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`idQuestion Type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Questions` (
  `idQuestions` INT NOT NULL AUTO_INCREMENT,
  `QuestionContent` LONGTEXT NULL,
  `CorrectMultiple` CHAR(1) NULL DEFAULT 'N/A',
  `CorrectNumeric` INT ZEROFILL NULL,
  `CorrectNonNumeric` LONGTEXT NULL,
  PRIMARY KEY (`idQuestions`),
  CONSTRAINT `questionType`
    FOREIGN KEY (`idQuestions`)
    REFERENCES `mydb`.`Question Type` (`idQuestion Type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
